#!/bin/bash
### BEGIN INIT INFO
# Provides:          rash_watchdog
# Required-Start:    $remote_fs $network
# Required-Stop:     $remote_fs $network
# Default-Start:     3 5
# Default-Stop:      0 1 2 6
# Description:       Remote Application SHutdown watchdog
### END INIT INFO 

if [ ! -f /etc/rash/rash.conf ] ; then
	echo "Couldn't open /etc/rash/rash.conf"
	exit 1
fi
. /etc/rash/rash.conf

if [ $WATCHDOG_ACTIVE -ne 1 ] ; then
	echo "RASH-Watchdog has been disabled - /etc/rash.conf"
	exit 1
fi

# Must be a valid filename
NAME=rash_watchdog
PIDFILE=${WATCHDOG_PIDFILE}
 
export PATH="${PATH:+$PATH:}/usr/sbin:/sbin"
 
case "$1" in
  start)
        echo "Starting daemon: "$NAME
	if [ ! -f ${WATCHDOG_PIDFILE} ] ; then
		sudo -u ${RASH_USER} -H /bin/bash /usr/local/bin/rash_watchdog.sh &>/dev/null &
		PID=$!
		echo $PID > ${WATCHDOG_PIDFILE}
	fi
	;;
  stop)
        echo "Stopping daemon: "$NAME
	if [ -f ${WATCHDOG_PIDFILE} ] ; then
		kill -9 $(cat ${WATCHDOG_PIDFILE})
		rm -f ${WATCHDOG_PIDFILE}
	fi
	;;
  restart)
	$0 stop
	$0 start
	;;
  status)
	if [ -f ${WATCHDOG_PIDFILE} ] ; then
		echo "Daemon is running..."
		exit 0
	else
		echo "Daemon is not running..."
		exit 1
	fi
	;; 
  *)
	echo "Usage: "$1" {start|stop|restart|status}"
	exit 1
esac
 
exit 0
